# Generated by Django 5.2.1 on 2025-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30, verbose_name='libelle')),
                ('prix', models.FloatField()),
                ('quantite', models.FloatField()),
                ('unite', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
