# Generated by Django 5.2.1 on 2025-05-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categorie'),
        ),
    ]
